#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.20.2

pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            # Build compiles the packages
            - make
